### ISSUE TITLE
help with setup

### ISSUE THREAD

**Issue by jaredh159** [mnemnion/obelizmo#1]
Hi thanks for the library! I'm brand new to zig, so I'm almost certainly doing something super stupid, but I haven't been able to follow the install instructions and get this package to work. Would you be able to tell me what I'm missing?

Here's the commit where I tried to add your library:

https://github.com/jaredh159/zig-monkey/commit/80f77c29d09a0a0395a0f630bea63204e303b7a5

But I'm getting:

```txt
src/lexer.zig:29:24: error: no module named 'ohsnap' available within module test
const OhSnap = @import("ohsnap");
                       ^~~~~~~~
```

I dug up one of your other repos where you use ohsnap as well, but I can't see the difference between what you did, and what I tried to do. It's not a zig version thing is it? I'm running `0.15.0-dev.483+837e0f9c3` in case it matters.

Thanks so much! 🙏

**Comment by mnemnion** [comment]
Hi,

`obelizmo` was not Zig `0.15` compatible until... today, as it happens. 

The latest release should work with `0.15.1`.  Support for `zig master` is not a high priority for this project.
